// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n';

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = 'zh';

export type Locales = 'en' | 'zh';

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
  /**
   * 你​好​ ​{​n​a​m​e​}​!​ ​当​前​展​示​的​是​ ​{​l​o​c​a​l​e​}​ ​语​言
   * @param {string} locale
   * @param {string} name
   */
  HI: RequiredParams<'locale' | 'name'>;
};

export type TranslationFunctions = {
  /**
   * 你好 {name}! 当前展示的是 {locale} 语言
   */
  HI: (arg: { locale: string; name: string }) => LocalizedString;
};

export type Formatters = {};
