// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * H​i​ ​{​n​a​m​e​}​!​ ​n​o​w​ ​s​h​o​w​i​n​g​ ​{​l​o​c​a​l​e​}​ ​l​a​n​g​u​a​g​e
	 * @param {unknown} locale
	 * @param {unknown} name
	 */
	HI: RequiredParams<'locale' | 'name'>
	common: {
		/**
		 * S​w​i​t​c​h​ ​l​a​n​g​u​a​g​e
		 */
		languageToggle: string
		/**
		 * T​h​i​s​ ​f​e​a​t​u​r​e​ ​i​s​ ​n​o​t​ ​a​v​a​i​l​a​b​l​e​ ​y​e​t
		 */
		notImplemented: string
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
		/**
		 * D​e​l​e​t​e
		 */
		'delete': string
		/**
		 * E​d​i​t
		 */
		edit: string
		/**
		 * E​r​r​o​r
		 */
		error: string
		/**
		 * N​o​t​i​c​e
		 */
		notice: string
		/**
		 * C​o​p​i​e​d
		 */
		copied: string
		/**
		 * C​o​n​t​e​n​t​ ​c​o​p​i​e​d​ ​t​o​ ​c​l​i​p​b​o​a​r​d
		 */
		contentCopied: string
		/**
		 * T​o​d​a​y
		 */
		today: string
		/**
		 * Y​e​s​t​e​r​d​a​y
		 */
		yesterday: string
		/**
		 * T​h​i​s​ ​W​e​e​k
		 */
		thisWeek: string
		/**
		 * T​h​i​s​ ​M​o​n​t​h
		 */
		thisMonth: string
	}
	tabs: {
		/**
		 * H​o​m​e
		 */
		home: string
		/**
		 * M​i​n​e
		 */
		mine: string
		/**
		 * D​i​s​c​o​v​e​r
		 */
		discover: string
	}
	routes: {
		/**
		 * L​o​g​i​n
		 */
		login: string
		/**
		 * P​r​o​t​e​c​t​e​d​ ​C​o​n​t​e​n​t
		 */
		'protected': string
		/**
		 * S​e​t​t​i​n​g​s
		 */
		settings: string
		/**
		 * P​r​i​v​a​c​y​ ​P​o​l​i​c​y
		 */
		privacyPolicy: string
		/**
		 * F​A​Q
		 */
		qa: string
		/**
		 * S​c​a​n
		 */
		scan: string
		/**
		 * H​i​s​t​o​r​y
		 */
		scanHistory: string
		/**
		 * M​e​d​i​a​ ​P​r​e​v​i​e​w
		 */
		mediaViewer: string
		/**
		 * S​u​p​p​o​r​t​ ​c​h​a​t
		 */
		onlineService: string
		/**
		 * D​e​l​e​t​e​ ​A​c​c​o​u​n​t
		 */
		destroyAccount: string
		/**
		 * N​o​t​i​f​i​c​a​t​i​o​n​s
		 */
		notices: string
	}
	settings: {
		/**
		 * B​u​s​i​n​e​s​s​ ​L​i​c​e​n​s​e
		 */
		businessLicense: string
		/**
		 * P​r​i​v​a​c​y​ ​S​e​t​t​i​n​g​s
		 */
		privacySettings: string
		/**
		 * C​l​e​a​r​ ​C​a​c​h​e
		 */
		clearCache: string
		/**
		 * N​e​t​w​o​r​k​ ​D​i​a​g​n​o​s​t​i​c​s
		 */
		networkDiagnostics: string
		/**
		 * P​e​r​s​o​n​a​l​ ​I​n​f​o​r​m​a​t​i​o​n​ ​C​o​l​l​e​c​t​i​o​n​ ​a​n​d​ ​U​s​e​ ​L​i​s​t
		 */
		personalInfoCollectionUse: string
		/**
		 * P​e​r​s​o​n​a​l​ ​I​n​f​o​r​m​a​t​i​o​n​ ​S​h​a​r​e​d​ ​w​i​t​h​ ​T​h​i​r​d​ ​P​a​r​t​i​e​s
		 */
		personalInfoThirdPartySharing: string
		/**
		 * S​y​s​t​e​m​ ​P​e​r​m​i​s​s​i​o​n​ ​U​s​a​g​e​ ​L​i​s​t
		 */
		systemPermissionUsage: string
		/**
		 * A​l​g​o​r​i​t​h​m​ ​F​i​l​i​n​g
		 */
		algorithmFiling: string
		/**
		 * D​e​l​e​t​e​ ​A​c​c​o​u​n​t
		 */
		deleteAccount: string
		/**
		 * 1​M
		 */
		cacheSize: string
	}
	home: {
		/**
		 * N​o​ ​m​o​r​e​ ​i​t​e​m​s
		 */
		noMore: string
	}
	mine: {
		/**
		 * N​o​t​i​f​i​c​a​t​i​o​n​s
		 */
		notification: string
		/**
		 * H​e​l​p​ ​C​e​n​t​e​r
		 */
		helpCenter: string
		/**
		 * F​e​e​d​b​a​c​k
		 */
		feedback: string
		/**
		 * A​b​o​u​t​ ​U​s
		 */
		about: string
		/**
		 * P​h​o​n​e​ ​n​u​m​b​e​r​ ​n​o​t​ ​l​i​n​k​e​d
		 */
		phoneNotLinked: string
		/**
		 * S​i​g​n​ ​o​u​t
		 */
		signOut: string
		/**
		 * L​o​g​ ​i​n​ ​/​ ​S​i​g​n​ ​u​p
		 */
		loginOrRegister: string
	}
	notice: {
		/**
		 * N​o​ ​m​e​s​s​a​g​e​s
		 */
		empty: string
		/**
		 * N​o​t​i​c​e​ ​T​i​t​l​e​ ​{​i​d​}
		 * @param {unknown} id
		 */
		title: RequiredParams<'id'>
		/**
		 * T​h​i​s​ ​i​s​ ​m​e​s​s​a​g​e​ ​c​o​n​t​e​n​t​ ​{​i​d​}​,​ ​i​n​c​l​u​d​i​n​g​ ​i​m​p​o​r​t​a​n​t​ ​s​y​s​t​e​m​ ​n​o​t​i​f​i​c​a​t​i​o​n​s​.
		 * @param {unknown} id
		 */
		content: RequiredParams<'id'>
	}
	scan: {
		/**
		 * S​c​a​n​n​e​d​ ​C​o​n​t​e​n​t
		 */
		contentTitle: string
		/**
		 * C​o​p​y
		 */
		copy: string
		/**
		 * C​l​o​s​e
		 */
		close: string
		/**
		 * C​a​m​e​r​a​ ​p​e​r​m​i​s​s​i​o​n​ ​i​s​ ​r​e​q​u​i​r​e​d​ ​t​o​ ​s​c​a​n​ ​Q​R​ ​c​o​d​e​s
		 */
		cameraPermission: string
		/**
		 * G​r​a​n​t​ ​A​c​c​e​s​s
		 */
		grantAccess: string
		/**
		 * N​o​ ​a​v​a​i​l​a​b​l​e​ ​c​a​m​e​r​a​ ​d​e​v​i​c​e​ ​f​o​u​n​d
		 */
		noCamera: string
		/**
		 * P​l​a​c​e​ ​t​h​e​ ​Q​R​ ​c​o​d​e​ ​i​n​s​i​d​e​ ​t​h​e​ ​f​r​a​m​e​ ​t​o​ ​s​c​a​n​ ​a​u​t​o​m​a​t​i​c​a​l​l​y​.
		 */
		instruction: string
		/**
		 * F​l​a​s​h​l​i​g​h​t
		 */
		flashlight: string
		/**
		 * C​h​o​o​s​e​ ​f​r​o​m​ ​A​l​b​u​m
		 */
		chooseFromAlbum: string
		/**
		 * H​i​s​t​o​r​y
		 */
		history: string
		/**
		 * S​c​a​n​ ​A​g​a​i​n
		 */
		scanAgain: string
		/**
		 * P​e​r​m​i​s​s​i​o​n​ ​R​e​q​u​i​r​e​d
		 */
		albumPermissionTitle: string
		/**
		 * A​l​l​o​w​ ​a​l​b​u​m​ ​a​c​c​e​s​s​ ​t​o​ ​c​h​o​o​s​e​ ​a​n​ ​i​m​a​g​e
		 */
		albumPermissionMessage: string
		/**
		 * P​r​o​c​e​s​s​i​n​g
		 */
		processingTitle: string
		/**
		 * R​e​c​o​g​n​i​z​i​n​g​ ​t​h​e​ ​Q​R​ ​c​o​d​e​ ​i​n​ ​t​h​e​ ​i​m​a​g​e​.​.​.
		 */
		processingMessage: string
		/**
		 * R​e​c​o​g​n​i​t​i​o​n​ ​F​a​i​l​e​d
		 */
		recognitionFailedTitle: string
		/**
		 * C​o​u​l​d​ ​n​o​t​ ​r​e​c​o​g​n​i​z​e​ ​a​ ​Q​R​ ​c​o​d​e​ ​i​n​ ​t​h​e​ ​i​m​a​g​e​.​ ​M​a​k​e​ ​s​u​r​e​ ​i​t​ ​i​s​ ​c​l​e​a​r​ ​a​n​d​ ​v​a​l​i​d​.
		 */
		recognitionFailedMessage: string
		/**
		 * A​n​ ​e​r​r​o​r​ ​o​c​c​u​r​r​e​d​ ​w​h​i​l​e​ ​s​e​l​e​c​t​i​n​g​ ​a​n​ ​i​m​a​g​e
		 */
		imagePickError: string
	}
	scanHistory: {
		/**
		 * S​e​l​e​c​t​ ​A​l​l
		 */
		selectAll: string
		/**
		 * C​o​n​f​i​r​m​ ​D​e​l​e​t​e
		 */
		deleteConfirmTitle: string
		/**
		 * D​e​l​e​t​e​ ​t​h​i​s​ ​r​e​c​o​r​d​?
		 */
		deleteOneConfirm: string
		/**
		 * S​e​l​e​c​t​ ​r​e​c​o​r​d​s​ ​t​o​ ​d​e​l​e​t​e​ ​f​i​r​s​t
		 */
		selectBeforeDelete: string
		/**
		 * D​e​l​e​t​e​ ​{​c​o​u​n​t​}​ ​s​e​l​e​c​t​e​d​ ​r​e​c​o​r​d​s​?
		 * @param {unknown} count
		 */
		deleteSelectedConfirm: RequiredParams<'count'>
		/**
		 * N​o​ ​s​c​a​n​ ​h​i​s​t​o​r​y
		 */
		emptyTitle: string
		/**
		 * Q​R​ ​c​o​d​e​ ​s​c​a​n​s​ ​w​i​l​l​ ​b​e​ ​s​a​v​e​d​ ​h​e​r​e​ ​a​u​t​o​m​a​t​i​c​a​l​l​y
		 */
		emptyDescription: string
		/**
		 * S​c​a​n​ ​n​o​w
		 */
		scanNow: string
	}
	qa: {
		/**
		 * S​e​a​r​c​h​ ​q​u​e​s​t​i​o​n​s
		 */
		searchPlaceholder: string
		/**
		 * N​o​ ​m​a​t​c​h​i​n​g​ ​q​u​e​s​t​i​o​n​s​ ​f​o​u​n​d​.​ ​T​r​y​ ​a​n​o​t​h​e​r​ ​k​e​y​w​o​r​d​.
		 */
		noResults: string
		/**
		 * A​l​l
		 */
		all: string
	}
	feedback: {
		/**
		 * S​e​l​e​c​t​ ​a​n​ ​i​s​s​u​e​ ​t​a​g
		 */
		selectTag: string
		/**
		 * A​c​c​u​r​a​t​e​ ​c​a​t​e​g​o​r​i​e​s​ ​h​e​l​p​ ​u​s​ ​r​e​s​p​o​n​d​ ​f​a​s​t​e​r
		 */
		selectTagDescription: string
		/**
		 * F​e​e​d​b​a​c​k​ ​T​i​t​l​e​ ​a​n​d​ ​C​o​n​t​e​n​t
		 */
		titleAndContent: string
		/**
		 * T​i​t​l​e​ ​(​u​p​ ​t​o​ ​3​0​ ​c​h​a​r​a​c​t​e​r​s​)
		 */
		titlePlaceholder: string
		/**
		 * Y​o​u​r​ ​s​u​g​g​e​s​t​i​o​n​s​ ​h​e​l​p​ ​u​s​ ​i​m​p​r​o​v​e
		 */
		contentPlaceholder: string
		/**
		 * U​p​l​o​a​d​ ​P​h​o​t​o​s
		 */
		uploadPhotos: string
		/**
		 * U​p​l​o​a​d​ ​s​c​r​e​e​n​s​h​o​t​s​ ​o​r​ ​p​h​o​t​o​s​ ​t​o​ ​h​e​l​p​ ​u​s​ ​u​n​d​e​r​s​t​a​n​d​ ​t​h​e​ ​i​s​s​u​e​.
		 */
		uploadPhotosDescription: string
		/**
		 * S​u​b​m​i​t
		 */
		submit: string
		/**
		 * F​e​e​d​b​a​c​k​ ​s​u​b​m​i​t​t​e​d
		 */
		submitted: string
		types: {
			/**
			 * B​u​g​ ​R​e​p​o​r​t
			 */
			bug: string
			/**
			 * C​o​m​p​l​a​i​n​t
			 */
			complaint: string
			/**
			 * F​e​e​d​b​a​c​k
			 */
			feedback: string
			/**
			 * C​r​e​d​i​t​ ​I​s​s​u​e
			 */
			credit: string
			/**
			 * L​o​a​n​ ​I​s​s​u​e
			 */
			loan: string
			/**
			 * R​e​p​a​y​m​e​n​t​ ​I​s​s​u​e
			 */
			repayment: string
			/**
			 * O​t​h​e​r
			 */
			other: string
		}
	}
	login: {
		/**
		 * U​s​e​r​n​a​m​e
		 */
		usernamePlaceholder: string
		/**
		 * P​a​s​s​w​o​r​d
		 */
		passwordPlaceholder: string
		/**
		 * L​o​g​i​n
		 */
		submit: string
		/**
		 * o​r
		 */
		or: string
		/**
		 * L​o​g​i​n​ ​w​i​t​h​ ​G​i​t​H​u​b
		 */
		github: string
		/**
		 * B​a​c​k
		 */
		back: string
		/**
		 * E​n​t​e​r​ ​u​s​e​r​n​a​m​e​ ​a​n​d​ ​p​a​s​s​w​o​r​d
		 */
		missingCredentials: string
		/**
		 * L​o​g​i​n​ ​f​a​i​l​e​d​.​ ​C​h​e​c​k​ ​y​o​u​r​ ​u​s​e​r​n​a​m​e​ ​a​n​d​ ​p​a​s​s​w​o​r​d​.
		 */
		failed: string
	}
	discover: {
		/**
		 * S​e​a​r​c​h​ ​f​e​a​t​u​r​e​s​,​ ​d​e​s​c​r​i​p​t​i​o​n​s​,​ ​o​r​ ​p​l​a​t​f​o​r​m​s​.​.​.
		 */
		searchPlaceholder: string
		/**
		 * N​o​ ​m​a​t​c​h​i​n​g​ ​i​t​e​m​s​ ​f​o​u​n​d
		 */
		noResults: string
	}
	privacy: {
		/**
		 * P​r​i​v​a​c​y​ ​P​o​l​i​c​y
		 */
		title: string
		/**
		 * L​a​s​t​ ​u​p​d​a​t​e​d​:​ ​A​p​r​i​l​ ​1​5​,​ ​2​0​2​5
		 */
		lastUpdated: string
		/**
		 * 1​.​ ​I​n​f​o​r​m​a​t​i​o​n​ ​C​o​l​l​e​c​t​i​o​n
		 */
		section1: string
		/**
		 * 2​.​ ​I​n​f​o​r​m​a​t​i​o​n​ ​U​s​e
		 */
		section2: string
		/**
		 * 3​.​ ​I​n​f​o​r​m​a​t​i​o​n​ ​S​h​a​r​i​n​g
		 */
		section3: string
		/**
		 * 4​.​ ​D​a​t​a​ ​S​t​o​r​a​g​e​ ​a​n​d​ ​S​e​c​u​r​i​t​y
		 */
		section4: string
		/**
		 * 5​.​ ​Y​o​u​r​ ​R​i​g​h​t​s
		 */
		section5: string
		/**
		 * 6​.​ ​C​h​i​l​d​r​e​n​'​s​ ​P​r​i​v​a​c​y
		 */
		section6: string
		/**
		 * 7​.​ ​P​r​i​v​a​c​y​ ​P​o​l​i​c​y​ ​C​h​a​n​g​e​s
		 */
		section7: string
		/**
		 * 8​.​ ​C​o​n​t​a​c​t​ ​U​s
		 */
		section8: string
	}
}

export type TranslationFunctions = {
	/**
	 * Hi {name}! now showing {locale} language
	 */
	HI: (arg: { locale: unknown, name: unknown }) => LocalizedString
	common: {
		/**
		 * Switch language
		 */
		languageToggle: () => LocalizedString
		/**
		 * This feature is not available yet
		 */
		notImplemented: () => LocalizedString
		/**
		 * Cancel
		 */
		cancel: () => LocalizedString
		/**
		 * Delete
		 */
		'delete': () => LocalizedString
		/**
		 * Edit
		 */
		edit: () => LocalizedString
		/**
		 * Error
		 */
		error: () => LocalizedString
		/**
		 * Notice
		 */
		notice: () => LocalizedString
		/**
		 * Copied
		 */
		copied: () => LocalizedString
		/**
		 * Content copied to clipboard
		 */
		contentCopied: () => LocalizedString
		/**
		 * Today
		 */
		today: () => LocalizedString
		/**
		 * Yesterday
		 */
		yesterday: () => LocalizedString
		/**
		 * This Week
		 */
		thisWeek: () => LocalizedString
		/**
		 * This Month
		 */
		thisMonth: () => LocalizedString
	}
	tabs: {
		/**
		 * Home
		 */
		home: () => LocalizedString
		/**
		 * Mine
		 */
		mine: () => LocalizedString
		/**
		 * Discover
		 */
		discover: () => LocalizedString
	}
	routes: {
		/**
		 * Login
		 */
		login: () => LocalizedString
		/**
		 * Protected Content
		 */
		'protected': () => LocalizedString
		/**
		 * Settings
		 */
		settings: () => LocalizedString
		/**
		 * Privacy Policy
		 */
		privacyPolicy: () => LocalizedString
		/**
		 * FAQ
		 */
		qa: () => LocalizedString
		/**
		 * Scan
		 */
		scan: () => LocalizedString
		/**
		 * History
		 */
		scanHistory: () => LocalizedString
		/**
		 * Media Preview
		 */
		mediaViewer: () => LocalizedString
		/**
		 * Support chat
		 */
		onlineService: () => LocalizedString
		/**
		 * Delete Account
		 */
		destroyAccount: () => LocalizedString
		/**
		 * Notifications
		 */
		notices: () => LocalizedString
	}
	settings: {
		/**
		 * Business License
		 */
		businessLicense: () => LocalizedString
		/**
		 * Privacy Settings
		 */
		privacySettings: () => LocalizedString
		/**
		 * Clear Cache
		 */
		clearCache: () => LocalizedString
		/**
		 * Network Diagnostics
		 */
		networkDiagnostics: () => LocalizedString
		/**
		 * Personal Information Collection and Use List
		 */
		personalInfoCollectionUse: () => LocalizedString
		/**
		 * Personal Information Shared with Third Parties
		 */
		personalInfoThirdPartySharing: () => LocalizedString
		/**
		 * System Permission Usage List
		 */
		systemPermissionUsage: () => LocalizedString
		/**
		 * Algorithm Filing
		 */
		algorithmFiling: () => LocalizedString
		/**
		 * Delete Account
		 */
		deleteAccount: () => LocalizedString
		/**
		 * 1M
		 */
		cacheSize: () => LocalizedString
	}
	home: {
		/**
		 * No more items
		 */
		noMore: () => LocalizedString
	}
	mine: {
		/**
		 * Notifications
		 */
		notification: () => LocalizedString
		/**
		 * Help Center
		 */
		helpCenter: () => LocalizedString
		/**
		 * Feedback
		 */
		feedback: () => LocalizedString
		/**
		 * About Us
		 */
		about: () => LocalizedString
		/**
		 * Phone number not linked
		 */
		phoneNotLinked: () => LocalizedString
		/**
		 * Sign out
		 */
		signOut: () => LocalizedString
		/**
		 * Log in / Sign up
		 */
		loginOrRegister: () => LocalizedString
	}
	notice: {
		/**
		 * No messages
		 */
		empty: () => LocalizedString
		/**
		 * Notice Title {id}
		 */
		title: (arg: { id: unknown }) => LocalizedString
		/**
		 * This is message content {id}, including important system notifications.
		 */
		content: (arg: { id: unknown }) => LocalizedString
	}
	scan: {
		/**
		 * Scanned Content
		 */
		contentTitle: () => LocalizedString
		/**
		 * Copy
		 */
		copy: () => LocalizedString
		/**
		 * Close
		 */
		close: () => LocalizedString
		/**
		 * Camera permission is required to scan QR codes
		 */
		cameraPermission: () => LocalizedString
		/**
		 * Grant Access
		 */
		grantAccess: () => LocalizedString
		/**
		 * No available camera device found
		 */
		noCamera: () => LocalizedString
		/**
		 * Place the QR code inside the frame to scan automatically.
		 */
		instruction: () => LocalizedString
		/**
		 * Flashlight
		 */
		flashlight: () => LocalizedString
		/**
		 * Choose from Album
		 */
		chooseFromAlbum: () => LocalizedString
		/**
		 * History
		 */
		history: () => LocalizedString
		/**
		 * Scan Again
		 */
		scanAgain: () => LocalizedString
		/**
		 * Permission Required
		 */
		albumPermissionTitle: () => LocalizedString
		/**
		 * Allow album access to choose an image
		 */
		albumPermissionMessage: () => LocalizedString
		/**
		 * Processing
		 */
		processingTitle: () => LocalizedString
		/**
		 * Recognizing the QR code in the image...
		 */
		processingMessage: () => LocalizedString
		/**
		 * Recognition Failed
		 */
		recognitionFailedTitle: () => LocalizedString
		/**
		 * Could not recognize a QR code in the image. Make sure it is clear and valid.
		 */
		recognitionFailedMessage: () => LocalizedString
		/**
		 * An error occurred while selecting an image
		 */
		imagePickError: () => LocalizedString
	}
	scanHistory: {
		/**
		 * Select All
		 */
		selectAll: () => LocalizedString
		/**
		 * Confirm Delete
		 */
		deleteConfirmTitle: () => LocalizedString
		/**
		 * Delete this record?
		 */
		deleteOneConfirm: () => LocalizedString
		/**
		 * Select records to delete first
		 */
		selectBeforeDelete: () => LocalizedString
		/**
		 * Delete {count} selected records?
		 */
		deleteSelectedConfirm: (arg: { count: unknown }) => LocalizedString
		/**
		 * No scan history
		 */
		emptyTitle: () => LocalizedString
		/**
		 * QR code scans will be saved here automatically
		 */
		emptyDescription: () => LocalizedString
		/**
		 * Scan now
		 */
		scanNow: () => LocalizedString
	}
	qa: {
		/**
		 * Search questions
		 */
		searchPlaceholder: () => LocalizedString
		/**
		 * No matching questions found. Try another keyword.
		 */
		noResults: () => LocalizedString
		/**
		 * All
		 */
		all: () => LocalizedString
	}
	feedback: {
		/**
		 * Select an issue tag
		 */
		selectTag: () => LocalizedString
		/**
		 * Accurate categories help us respond faster
		 */
		selectTagDescription: () => LocalizedString
		/**
		 * Feedback Title and Content
		 */
		titleAndContent: () => LocalizedString
		/**
		 * Title (up to 30 characters)
		 */
		titlePlaceholder: () => LocalizedString
		/**
		 * Your suggestions help us improve
		 */
		contentPlaceholder: () => LocalizedString
		/**
		 * Upload Photos
		 */
		uploadPhotos: () => LocalizedString
		/**
		 * Upload screenshots or photos to help us understand the issue.
		 */
		uploadPhotosDescription: () => LocalizedString
		/**
		 * Submit
		 */
		submit: () => LocalizedString
		/**
		 * Feedback submitted
		 */
		submitted: () => LocalizedString
		types: {
			/**
			 * Bug Report
			 */
			bug: () => LocalizedString
			/**
			 * Complaint
			 */
			complaint: () => LocalizedString
			/**
			 * Feedback
			 */
			feedback: () => LocalizedString
			/**
			 * Credit Issue
			 */
			credit: () => LocalizedString
			/**
			 * Loan Issue
			 */
			loan: () => LocalizedString
			/**
			 * Repayment Issue
			 */
			repayment: () => LocalizedString
			/**
			 * Other
			 */
			other: () => LocalizedString
		}
	}
	login: {
		/**
		 * Username
		 */
		usernamePlaceholder: () => LocalizedString
		/**
		 * Password
		 */
		passwordPlaceholder: () => LocalizedString
		/**
		 * Login
		 */
		submit: () => LocalizedString
		/**
		 * or
		 */
		or: () => LocalizedString
		/**
		 * Login with GitHub
		 */
		github: () => LocalizedString
		/**
		 * Back
		 */
		back: () => LocalizedString
		/**
		 * Enter username and password
		 */
		missingCredentials: () => LocalizedString
		/**
		 * Login failed. Check your username and password.
		 */
		failed: () => LocalizedString
	}
	discover: {
		/**
		 * Search features, descriptions, or platforms...
		 */
		searchPlaceholder: () => LocalizedString
		/**
		 * No matching items found
		 */
		noResults: () => LocalizedString
	}
	privacy: {
		/**
		 * Privacy Policy
		 */
		title: () => LocalizedString
		/**
		 * Last updated: April 15, 2025
		 */
		lastUpdated: () => LocalizedString
		/**
		 * 1. Information Collection
		 */
		section1: () => LocalizedString
		/**
		 * 2. Information Use
		 */
		section2: () => LocalizedString
		/**
		 * 3. Information Sharing
		 */
		section3: () => LocalizedString
		/**
		 * 4. Data Storage and Security
		 */
		section4: () => LocalizedString
		/**
		 * 5. Your Rights
		 */
		section5: () => LocalizedString
		/**
		 * 6. Children's Privacy
		 */
		section6: () => LocalizedString
		/**
		 * 7. Privacy Policy Changes
		 */
		section7: () => LocalizedString
		/**
		 * 8. Contact Us
		 */
		section8: () => LocalizedString
	}
}

export type Formatters = {}
